# Added -n (number of concurrent tests) and --dist=loadscope (load by class) for concurrency with pytest-xdist plugin
[tool.pytest.ini_options]
addopts = "--maxfail=1 --verbose -s -n=auto --dist loadscope"
testpaths = [
    "tests"
]

# Omit /builder/* so Coverage doesn't evaluate all installed packages when running on Cloud Build, etc.
[tool.coverage.run]
omit = [
    "/builder/*",
    "tests/*",
    "venv/*",
]

[tool.coverage.report]
show_missing = true
