# Create GitHub Build Trigger
# https://cloud.google.com/sdk/gcloud/reference/beta/builds/triggers/create/github
# https://cloud.google.com/config-connector/docs/reference/resource-docs/cloudbuild/cloudbuildtrigger

description: {{ cookiecutter.project_name }} PR to Main Build Trigger
filename: "GIT_REPO_ROOT_PLACEHOLDER/cloudbuild/cloudbuild.yaml"
github:
  name: GIT_REPO_ROOT_PLACEHOLDER
  owner: GIT_REPO_OWNER_PLACEHOLDER
  pullRequest:
    branch: ^master|main$
    commentControl: COMMENTS_ENABLED_FOR_EXTERNAL_CONTRIBUTORS_ONLY
ignoredFiles:
- '**/*.md'
includedFiles:
- "GIT_REPO_ROOT_PLACEHOLDER"
name: {{ cookiecutter.project_slug }}-pr-to-main
includeBuildLogs: "INCLUDE_BUILD_LOGS_WITH_STATUS"

# TODO: Since using setup project script, could replace the values in the CICD setup part, and fetch/initalize git repo in setup
# TODO: still need post hook to add/remove file... so just best to do so there and once-time generate the full directory and files 
# TODO: how to tell who the owner is?